### ISSUE TITLE
Not cloning base type fields

### ISSUE THREAD

**Issue by beachmaster** [Burtsev-Alexey/net-object-deep-copy#1]
Hi,

I recently saw a link to your cloning methods from stackoverflow and decided to try them out. I had my own methods that used a similar method, but I was creating my deep clone instances using Activator instead of MemberwiseClone, and your way has less side effects. However, I noticed that it only clones the private fields of the original object type and not fields of the objects base type(s) (if any).

The following change will take care of that:

```
Type reflectingType = originalType
while (reflectingType != null)
{
    foreach (.....
    {
        // nothing changed here
    }
    reflectingType = reflectingType.BaseType
}
```

Again, great work on this deep-clone, love it.

Tim

**Comment by DemoJameson** [comment]
`FlattenHierarchy` only work for static members, so its redundant

**Comment by Burtsev-Alexey** [comment]
> `FlattenHierarchy` only work for static members, so its redundant

You are right.
