### ISSUE TITLE
Is the repository maintained?

### ISSUE THREAD

**Issue by MNF** [Burtsev-Alexey/net-object-deep-copy#24]
Alexey, you have a few opened issues and pull requests( some of them possibly address the issues).
Could you please spend some time to clean up the log. Alternatively please specify in readme, that the repository is not maintained any more and provide an option either use other fork(e.g. from  pull request https://github.com/chivandikwa/net-object-deep-copy) or suggest someone to become a maintainer of this repository. It is still useful.

Alternatively, refer in Readme.md to some other project, that address the Clone , e.g. https://www.codeproject.com/Articles/1111658/Fast-Deep-Copy-of-Objects-by-Expression-Trees-Csha

Spasibo.

**Comment by Burtsev-Alexey** [comment]
Yeah it is maintained, when I have time. I use the same cloning code in projects I work for.
