### ISSUE TITLE
Using Copy on a simple boxed object doesn't clone the value

### ISSUE THREAD

**Issue by xMRi** [Burtsev-Alexey/net-object-deep-copy#26]
I have an object (mostly filled with primitives). It is not possible to clone such an object
The following code returnes the same object.
I would expect that I get always a new object.

```
var ob = (object)(int)5;
var ob2 = Clone(ob);
```

**Comment by jpmikkers** [comment]
Why? The boxed integer is immutable, so if you change the boxed value in a clone, it will get assigned a ref to a new boxed integer anyway.

**Comment by xMRi** [comment]
No. Boxed values are not immutable. 
https://stackoverflow.com/questions/7150768/why-does-the-clr-allow-mutating-boxed-immutable-value-types

But you are right for C#... because I sometimes use C++/CLI I got this effect here...
