### ISSUE TITLE
Type not Recogniced after Copy

### ISSUE THREAD

**Issue by robbymeier** [Burtsev-Alexey/net-object-deep-copy#27]
For some reason Type is not being recognized anymore even when using UnderlyingSystemType. Please see the following code:

class A {
   public A() {Type = typeof(string); }
   public Type Type { get; }
}

class Program {
   static void Main(string[] args) {
      A a1 = new A();
      A a2 = ObjectExtensions.Copy(a1);
      Console.WriteLine(String.Format("a1.Type {0} typeof(string)", (a1.Type == typeof(string)) ? "==" : "!="));
      Console.WriteLine(String.Format("a2.Type {0} typeof(string)", (a2.Type == typeof(string)) ? "==" : "!="));
    }
}

Why do I get different results from the clones object vs. the original object?

**Comment by Burtsev-Alexey** [comment]
Hello. That's an interesting observation.
I did some short research (less then 10 minutes), and short my short answer: I don't know why its happening, the answer requires deep understanding of CLR (which I don;t have).

But I have some guess.
Consider this code:
```
            Assert.AreEqual(typeof(string), typeof(String)); //1
            Assert.IsTrue(typeof(String) == typeof(string)); //2
            Assert.IsTrue(Object.ReferenceEquals(typeof(String), typeof(string))); //3
            Assert.AreEqual(typeof(String), ObjectExtensions.Copy(typeof(String))); //this FAIL
```
The interesting thing is line 3, which tells us that though Type is class (and not struct), but typeof operator always returns same reference of Type when called multiple times "typeof(String)", so Type behaves like `Type<T>` singleton object, maintaining single reference for each `<T>`.

I compared states (all field values) of "typeof(String)" and "ObjectExtensions.Copy(typeof(String))" they are identical, except their object reference (pointer). So I suspect "==" Type  operator compares references with some internal singleton reference of internal CLR metadata containing loaded classes information.


And if you are not interested in understating of what is happening here and just need a fix ignore all the text above and I think you can fix the problem by changing this code:

```
        public static bool IsPrimitive(this Type type)
        {
            if (type == typeof(String)) return true;
            if (type == typeof(Type)) return true;
            return (type.IsValueType & type.IsPrimitive);
}
```
